# -*- mode: ruby -*-
# vi: set ft=ruby :
# This script uses the following vagrant plugins:
# vagrant plugin install vagrant-hostmanager

VAGRANTFILE_API_VERSION = '2'

mode = "default"

if mode == "default"
    # Default (SIP master branch) nodes
    NODES = [{ name: 'sip-01', ip: '192.168.101.101', cpus: 2, mem: 2048 }]
elsif mode == "docker_swarm"
    # Docker Swarm (paas_prototype) nodes
    NODES = [
      { name: 'sip-01', ip: '192.168.101.101', cpus: 1, mem: 1024
        # expose_ports: [ { id: 'docker-swarm', guest: 2377, host: 2377}, ]
      },
      { name: 'sip-02', ip: '192.168.101.102', cpus: 1, mem: 1024 }
    ]
end

puts "Nodes (#{mode}):"
NODES.each do |node|
    print("#{node}\n")
end
puts ""

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Hostmanager config
  # config.vm.provision :hostmanager
  # config.hostmanager.enabled = true
  # config.hostmanager.manage_host = true
  # config.hostmanager.manage_guest = true
  # config.hostmanager.ignore_private_ip = false
  # config.hostmanager.include_offline = true

  # Loop over set of defined nodes and set up VMs
  NODES.each do |node|
    config.vm.define node[:name] do |config|

      config.vm.box = "ubuntu/xenial64"
      config.vm.hostname = node[:name].to_s

      # Provision network interface
      config.vm.network :private_network, ip: node[:ip]
      # http://ermaker.github.io/blog/2015/11/18/change-insecure-key-to-my-own-key-on-vagrant.html
      config.ssh.private_key_path = ['keys/private', '~/.vagrant.d/insecure_private_key']
      config.ssh.insert_key = false
      config.vm.provision :file, source: "keys/public", destination: "~/.ssh/authorized_keys"
      config.vm.provision :file, source: "keys/public", destination: "~/.ssh/id_rsa.pub"
      config.vm.provision :file, source: "keys/private", destination: "~/.ssh/id_rsa"
      config.vm.provision :shell, :inline => "chmod 600 /home/ubuntu/.ssh/id_rsa"

      # Virtualbox configuration
      config.vm.provider :virtualbox do |vb|
        vb.name = node[:name].to_s
        vb.customize ['modifyvm', :id, '--cpus', node[:cpus]]
        vb.customize ['modifyvm', :id, '--memory', node[:mem]]
        # Needed for mac os?
        vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      end

      # Port forwards (NAT)
      if not node[:expose_ports].nil?
        if node[:expose_ports]
          node[:expose_ports].each do |ports|
            config.vm.network :forwarded_port, \
              guest: ports[:guest], \
              host: ports[:host], \
              id: ports[:id]
          end
        end
      end

    end
  end

end
